import Head from "next/head";
import Products from "@/components/Products";
import ProductsForm from "@/components/ProductsForm";
import { Poppins } from "@next/font/google";
import { QueryClientProvider, QueryClient } from "@tanstack/react-query";
import { ReactQueryDevtools } from "@tanstack/react-query-devtools";

const queryClient = new QueryClient();

const font = Poppins({
  weight: ["400", "700"],
  style: ["normal", "italic"],
  subsets: ["latin"],
});

export default function Home() {
  return (
    <QueryClientProvider client={queryClient}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex w-full flex-col items-center">
        <h1 className="mb-[10px]">Bienvenido al curso de React Query</h1>
        <ProductsForm />
        <Products />
      </main>
      <ReactQueryDevtools />
    </QueryClientProvider>
  );
}
